### ISSUE TITLE
Errors while building in Android

### ISSUE THREAD

**Issue by markgrancapal** [elastos/Elastos.SDK.DIDClient.Java#1]
I've added the SDK by adding this line of code on my gradle file:
`implementation group: 'org.elastos', name: 'did_client.lib', version: '1.1.0'`
or this one:
`implementation 'org.elastos:did_client.lib:1.1.2'`

and this error shows:
`Duplicate class org.apache.shiro.ShiroException found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.cache.AbstractCacheManager found in modules shiro-cache-1.4.0.jar (org.apache.shiro:shiro-cache:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.cache.Cache found in modules shiro-cache-1.4.0.jar (org.apache.shiro:shiro-cache:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.cache.CacheException found in modules shiro-cache-1.4.0.jar (org.apache.shiro:shiro-cache:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.cache.CacheManager found in modules shiro-cache-1.4.0.jar (org.apache.shiro:shiro-cache:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.cache.CacheManagerAware found in modules shiro-cache-1.4.0.jar (org.apache.shiro:shiro-cache:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.cache.MapCache found in modules shiro-cache-1.4.0.jar (org.apache.shiro:shiro-cache:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.cache.MemoryConstrainedCacheManager found in modules shiro-cache-1.4.0.jar (org.apache.shiro:shiro-cache:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.codec.Base64 found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.codec.CodecException found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.codec.CodecSupport found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.codec.H64 found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.codec.Hex found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.config.CommonsInterpolator found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.ConfigurationException found in the following modules: shiro-config-core-1.4.0.jar (org.apache.shiro:shiro-config-core:1.4.0), shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.DefaultInterpolator found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.Ini found in the following modules: shiro-config-core-1.4.0.jar (org.apache.shiro:shiro-config-core:1.4.0), shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.Ini$1 found in the following modules: shiro-config-core-1.4.0.jar (org.apache.shiro:shiro-config-core:1.4.0), shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.Ini$Section found in the following modules: shiro-config-core-1.4.0.jar (org.apache.shiro:shiro-config-core:1.4.0), shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.Interpolator found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.ReflectionBuilder found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.ReflectionBuilder$1 found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.ReflectionBuilder$AssignmentStatement found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.ReflectionBuilder$BeanConfiguration found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.ReflectionBuilder$BeanConfigurationProcessor found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.ReflectionBuilder$InstantiationStatement found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.ReflectionBuilder$Statement found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.ResourceConfigurable found in the following modules: shiro-config-core-1.4.0.jar (org.apache.shiro:shiro-config-core:1.4.0), shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.UnresolveableReferenceException found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.event.BeanEvent found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.event.ConfiguredBeanEvent found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.event.DestroyedBeanEvent found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.event.InitializedBeanEvent found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.event.InstantiatedBeanEvent found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.config.event.LoggingBeanEventListener found in modules shiro-config-ogdl-1.4.0.jar (org.apache.shiro:shiro-config-ogdl:1.4.0) and shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0)
Duplicate class org.apache.shiro.crypto.AbstractSymmetricCipherService found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0)
Duplicate class org.apache.shiro.crypto.AesCipherService found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0)
Duplicate class org.apache.shiro.crypto.BlowfishCipherService found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0)
Duplicate class org.apache.shiro.crypto.CipherService found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0)
Duplicate class org.apache.shiro.crypto.CryptoException found in the following modules: shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0), shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0) and shiro-crypto-core-1.4.0.jar (org.apache.shiro:shiro-crypto-core:1.4.0)
Duplicate class org.apache.shiro.crypto.DefaultBlockCipherService found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0)
Duplicate class org.apache.shiro.crypto.JcaCipherService found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0)
Duplicate class org.apache.shiro.crypto.OperationMode found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0)
Duplicate class org.apache.shiro.crypto.PaddingScheme found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0)
Duplicate class org.apache.shiro.crypto.RandomNumberGenerator found in the following modules: shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0), shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0) and shiro-crypto-core-1.4.0.jar (org.apache.shiro:shiro-crypto-core:1.4.0)
Duplicate class org.apache.shiro.crypto.SecureRandomNumberGenerator found in the following modules: shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0), shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0) and shiro-crypto-core-1.4.0.jar (org.apache.shiro:shiro-crypto-core:1.4.0)
Duplicate class org.apache.shiro.crypto.UnknownAlgorithmException found in the following modules: shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0), shiro-crypto-cipher-1.4.0.jar (org.apache.shiro:shiro-crypto-cipher:1.4.0) and shiro-crypto-core-1.4.0.jar (org.apache.shiro:shiro-crypto-core:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.AbstractHash found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.ConfigurableHashService found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.DefaultHashService found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.Hash found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.HashRequest found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.HashRequest$Builder found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.HashService found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.Md2Hash found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.Md5Hash found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.Sha1Hash found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.Sha256Hash found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.Sha384Hash found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.Sha512Hash found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.SimpleHash found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.SimpleHashRequest found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.format.Base64Format found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.format.DefaultHashFormatFactory found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.format.HashFormat found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.format.HashFormatFactory found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.format.HexFormat found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.format.ModularCryptFormat found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.format.ParsableHashFormat found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.format.ProvidedHashFormat found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.crypto.hash.format.Shiro1CryptFormat found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-crypto-hash-1.4.0.jar (org.apache.shiro:shiro-crypto-hash:1.4.0)
Duplicate class org.apache.shiro.event.Event found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.EventBus found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.EventBusAware found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.Subscribe found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.support.AnnotationEventListenerResolver found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.support.DefaultEventBus found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.support.DefaultEventBus$Subscription found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.support.EventClassComparator found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.support.EventListener found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.support.EventListenerComparator found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.support.EventListenerResolver found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.support.SingleArgumentMethodEventListener found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.event.support.TypedEventListener found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-event-1.4.0.jar (org.apache.shiro:shiro-event:1.4.0)
Duplicate class org.apache.shiro.io.ClassResolvingObjectInputStream found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.io.DefaultSerializer found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.io.ResourceUtils found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.io.SerializationException found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.io.Serializer found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.io.XmlSerializer found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.Assert found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.ByteSource found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.ByteSource$Util found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.ClassUtils found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.ClassUtils$1 found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.ClassUtils$2 found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.ClassUtils$3 found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.ClassUtils$ClassLoaderAccessor found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.ClassUtils$ExceptionIgnoringAccessor found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.Destroyable found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.Factory found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.Initializable found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.InstantiationException found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.LifecycleUtils found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.Nameable found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.SimpleByteSource found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.SimpleByteSource$1 found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.SimpleByteSource$BytesHelper found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.SoftHashMap found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.SoftHashMap$1 found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.SoftHashMap$SoftValue found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.StringUtils found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)
Duplicate class org.apache.shiro.util.UnknownClassException found in modules shiro-core-1.4.0.jar (org.apache.shiro:shiro-core:1.4.0) and shiro-lang-1.4.0.jar (org.apache.shiro:shiro-lang:1.4.0)`

![Screen Shot 2019-12-03 at 10 47 16 AM](https://user-images.githubusercontent.com/5191715/70016092-56a55e80-15ba-11ea-9c25-30a5504faef5.png)

**Comment by BenjaminPiette** [comment]
Hi Mark, this DID SDK is currently deprecated and will be replaced by the new DID SDK (supporting W3C specification) in the coming weeks. Sorry for the delay, keep in touch for the incoming DID SDK release.
